# Generated by Django 5.2 on 2025-04-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('niveau_etude', models.CharField(choices=[('Collège', 'Collège'), ('Lycée', 'Lycée'), ('Licence', 'Licence'), ('Master', 'Master'), ('Doctorat', 'Doctorat')], max_length=50)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10)),
            ],
        ),
    ]
