# Generated by Django 5.2 on 2025-04-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
