# Generated by Django 5.2 on 2025-04-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='events/videos/'),
        ),
    ]
